package core

type FieldType byte

const (
	// nonce字段
	XDAG_FIELD_NONCE FieldType = iota
	// 头部字段
	XDAG_FIELD_HEAD
	// 输入
	XDAG_FIELD_IN
	// 输入
	XDAG_FIELD_OUT
	// 输入签名
	XDAG_FIELD_SIGN_IN
	// 输出签名
	XDAG_FIELD_SIGN_OUT
	XDAG_FIELD_PUBLIC_KEY_0
	XDAG_FIELD_PUBLIC_KEY_1
	XDAG_FIELD_HEAD_TEST
	XDAG_FIELD_REMARK
	XDAG_FIELD_RESERVE1
	XDAG_FIELD_RESERVE2
	XDAG_FIELD_RESERVE3
	XDAG_FIELD_RESERVE4
	XDAG_FIELD_RESERVE5
	XDAG_FIELD_RESERVE6
)
